/*
 * TestUART.c
 *
 * Unit tests for the BspUart layer – STM32 <-> ESP32C3
 * Updated: May 02, 2026
 *
 */

#include "unity.h"
#include "UartCommon.h"
#include "Mockstm32f1xx_hal_uart.h"   /* CMock generated */

#include <string.h>

/* ── Fixtures ────────────────────────────────────────────────────────────── */

/*
 * Dummy handle that represents the handle MX_USART1_UART_Init() would
 * have filled in main.c.  Its contents do not matter for BSP tests –
 * only the pointer identity is relevant.
 */
static UART_HandleTypeDef sDummyHandle;

/* ── setUp / tearDown ───────────────────────────────────────────────────── */

void setUp(void)
{
    ResetBspUartState();
}

void tearDown(void)
{
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 1 – InitBspUart()
 *
 * MX_USART1_UART_Init() is generated by CubeMX and called in main.c before
 * any BSP function.  InitBspUart() therefore does NOT call HAL_UART_Init()
 * again – it only stores the already-initialised handle and sets the ready
 * flag.  No HAL mock is needed in this suite.
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 1.1
 * InitBspUart() with a valid handle must return BSP_UART_OK.
 * No HAL function should be called.
 */
void TestInitBspUartWithValidHandleReturnsOk(void)
{
    BspUartStatus_t ret = InitBspUart(&sDummyHandle);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
}

/*
 * Test case: 1.2
 * InitBspUart() with a NULL handle must return BSP_UART_ERR_NULL_PTR.
 * No HAL function should be called.
 */
void TestInitBspUartNullHandleReturnsError(void)
{
    BspUartStatus_t ret = InitBspUart(NULL);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NULL_PTR, ret);
}

/*
 * Test case: 1.3
 * Calling SendBspUart() before InitBspUart() must return BSP_UART_ERR_NOT_INIT.
 * ResetBspUartState() in setUp guarantees the init flag is cleared.
 */
void TestSendBspUartBeforeInitReturnsNotInit(void)
{
    uint8_t         data[] = {0x01, 0x02};
    BspUartStatus_t ret    = SendBspUart(&sDummyHandle, data, 2);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NOT_INIT, ret);
}

/*
 * Test case: 1.4
 * After a successful InitBspUart(), calling ResetBspUartState() and then
 * SendBspUart() must still return BSP_UART_ERR_NOT_INIT.
 *
 * This test exposes the missing init flag: if ResetBspUartState() does not
 * clear a dedicated mIsInitialized field, mCurrentStatus stays BSP_UART_OK
 * after reset and SendBspUart() skips the NOT_INIT guard entirely.
 */
void TestSendBspUartAfterResetReturnsNotInit(void)
{
    InitBspUart(&sDummyHandle);   /* mCurrentStatus = BSP_UART_OK */
    ResetBspUartState();          /* must also clear the init flag */

    uint8_t         data[] = {0x01, 0x02};
    BspUartStatus_t ret    = SendBspUart(&sDummyHandle, data, 2);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NOT_INIT, ret);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 2 – SendBspUart()
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 2.1
 * SendBspUart() must call HAL_UART_Transmit with the correct buffer and
 * length, and return BSP_UART_OK when HAL succeeds.
 */
void TestSendBspUartCallsHalTransmit(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0xAA, 0x01, 0x02, 0x55};

    HAL_UART_Transmit_ExpectAndReturn(
        &sDummyHandle, data, 4, BSP_UART_TX_TIMEOUT_MS, HAL_OK);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, data, 4);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
}

/*
 * Test case: 2.2
 * When HAL_UART_Transmit returns HAL_ERROR, SendBspUart() must return
 * BSP_UART_ERR_HAL.
 */
void TestSendBspUartHalErrorReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0x01};
    HAL_UART_Transmit_IgnoreAndReturn(HAL_ERROR);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, data, 1);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_HAL, ret);
}

/*
 * Test case: 2.3
 * Passing a NULL data pointer must return BSP_UART_ERR_NULL_PTR.
 * HAL_UART_Transmit must not be called.
 */
void TestSendBspUartNullPointerReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, NULL, 4);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NULL_PTR, ret);
}

/*
 * Test case: 2.4
 * Passing len = 0 must return BSP_UART_ERR_ZERO_LEN.
 * HAL_UART_Transmit must not be called.
 */
void TestSendBspUartZeroLenReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t         data[] = {0x01};
    BspUartStatus_t ret    = SendBspUart(&sDummyHandle, data, 0);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_ZERO_LEN, ret);
}

/*
 * Test case: 2.5
 * When HAL_UART_Transmit returns HAL_BUSY, SendBspUart() must return
 * BSP_UART_ERR_HAL.  Retry logic is not handled at this layer.
 */
void TestSendBspUartHalBusyReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0xAB, 0xCD};
    HAL_UART_Transmit_IgnoreAndReturn(HAL_BUSY);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, data, 2);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_HAL, ret);
}

/*
 * Test case: 2.6
 * After a failed HAL_UART_Transmit (HAL_BUSY), a subsequent SendBspUart()
 * call must still attempt transmission and return BSP_UART_OK on success.
 *
 * This exposes a state-poisoning bug: when HAL returns BUSY or ERROR,
 * the implementation sets mCurrentStatus = BSP_UART_ERR_HAL.  The next
 * call checks (mCurrentStatus != BSP_UART_OK) and returns BSP_UART_ERR_NOT_INIT
 * instead of proceeding – making the module permanently unusable after any
 * transient HAL failure, with no recovery path short of calling InitBspUart()
 * again.
 * Fix: do not modify mCurrentStatus on HAL transmit failure; only return
 * the error to the caller.
 */
void TestSendBspUartRetryAfterHalBusySucceeds(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0x01, 0x02};

    /* First attempt – HAL busy */
    HAL_UART_Transmit_IgnoreAndReturn(HAL_BUSY);
    BspUartStatus_t first = SendBspUart(&sDummyHandle, data, 2);
    TEST_ASSERT_EQUAL(BSP_UART_ERR_HAL, first);

    /* Retry – HAL now succeeds; must NOT return ERR_NOT_INIT */
    HAL_UART_Transmit_ExpectAndReturn(
        &sDummyHandle, data, 2, BSP_UART_TX_TIMEOUT_MS, HAL_OK);
    BspUartStatus_t retry = SendBspUart(&sDummyHandle, data, 2);
    TEST_ASSERT_EQUAL(BSP_UART_OK, retry);
}

/*
 * Test case: 2.7
 * After a call with a NULL data pointer, a subsequent call with a valid
 * pointer must still transmit and return BSP_UART_OK.
 *
 * Same state-poisoning pattern as TC 2.6: setting mCurrentStatus =
 * BSP_UART_ERR_NULL_PTR causes the next valid call to hit the NOT_INIT
 * guard and return BSP_UART_ERR_NOT_INIT instead of transmitting.
 * Fix: do not modify mCurrentStatus when rejecting a NULL or len=0 argument;
 * these are caller errors, not module-state transitions.
 */
void TestSendBspUartRetryAfterNullSucceeds(void)
{
    InitBspUart(&sDummyHandle);

    /* First call – NULL data, must be rejected */
    BspUartStatus_t first = SendBspUart(&sDummyHandle, NULL, 2);
    TEST_ASSERT_EQUAL(BSP_UART_ERR_NULL_PTR, first);

    /* Retry with valid data – must NOT return ERR_NOT_INIT */
    uint8_t data[] = {0x01, 0x02};
    HAL_UART_Transmit_ExpectAndReturn(
        &sDummyHandle, data, 2, BSP_UART_TX_TIMEOUT_MS, HAL_OK);
    BspUartStatus_t retry = SendBspUart(&sDummyHandle, data, 2);
    TEST_ASSERT_EQUAL(BSP_UART_OK, retry);
}

/*
 * Test case: 2.8
 * After a call with len = 0, a subsequent call with a valid len must still
 * transmit and return BSP_UART_OK.
 *
 * Same state-poisoning pattern: setting mCurrentStatus = BSP_UART_ERR_ZERO_LEN
 * blocks all future calls.
 * Fix: same as TC 2.7 – do not modify mCurrentStatus for argument errors.
 */
void TestSendBspUartRetryAfterZeroLenSucceeds(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0x01, 0x02};

    /* First call – zero len, must be rejected */
    BspUartStatus_t first = SendBspUart(&sDummyHandle, data, 0);
    TEST_ASSERT_EQUAL(BSP_UART_ERR_ZERO_LEN, first);

    /* Retry with valid len – must NOT return ERR_NOT_INIT */
    HAL_UART_Transmit_ExpectAndReturn(
        &sDummyHandle, data, 2, BSP_UART_TX_TIMEOUT_MS, HAL_OK);
    BspUartStatus_t retry = SendBspUart(&sDummyHandle, data, 2);
    TEST_ASSERT_EQUAL(BSP_UART_OK, retry);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 3 – HandleBspUartIsrRx() → ring buffer
 *
 * ISR handler is pure logic – no HAL calls, no CMock needed.
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 3.1
 * After pushing one byte via HandleBspUartIsrRx(), GetBspUartAvailable()
 * must return 1.
 */
void TestHandleIsrRxOneByteIsAvailable(void)
{
    HandleBspUartIsrRx(0xAB);

    TEST_ASSERT_EQUAL_UINT16(1, GetBspUartAvailable());
}

/*
 * Test case: 3.2
 * After pushing N bytes, GetBspUartAvailable() must return N.
 */
void TestHandleIsrRxMultipleBytesAvailable(void)
{
    HandleBspUartIsrRx(0x01);
    HandleBspUartIsrRx(0x02);
    HandleBspUartIsrRx(0x03);

    TEST_ASSERT_EQUAL_UINT16(3, GetBspUartAvailable());
}

/*
 * Test case: 3.3
 * Bytes pushed in order must be read back in FIFO order.
 */
void TestHandleIsrRxPreservesFifoOrder(void)
{
    HandleBspUartIsrRx(0xAA);
    HandleBspUartIsrRx(0xBB);
    HandleBspUartIsrRx(0xCC);

    uint8_t  buf[3] = {0};
    uint16_t nRead  = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 3, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(3,    nRead);
    TEST_ASSERT_EQUAL_HEX8(0xAA,  buf[0]);
    TEST_ASSERT_EQUAL_HEX8(0xBB,  buf[1]);
    TEST_ASSERT_EQUAL_HEX8(0xCC,  buf[2]);
}

/*
 * Test case: 3.4
 * Pushing a 0x00 byte must be readable as valid data, not treated as empty.
 */
void TestHandleIsrRxZeroBytePayloadIsReadable(void)
{
    HandleBspUartIsrRx(0x00);

    TEST_ASSERT_EQUAL_UINT16(1, GetBspUartAvailable());

    uint8_t  buf[1] = {0xFF};   /* pre-fill to detect non-write */
    uint16_t nRead  = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 1, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(1,    nRead);
    TEST_ASSERT_EQUAL_HEX8(0x00,  buf[0]);
}

/*
 * Test case: 3.5
 * When the ring buffer is full (256 bytes), the next byte pushed must be
 * dropped and IsBspUartOverflow() must return true.
 * The 256 bytes already in the buffer must be preserved without corruption.
 *
 */
void TestHandleIsrRxOverflowSetsFlag(void)
{
    for (uint16_t i = 0; i < BSP_UART_RX_RING_BUF_SIZE; i++) {
        HandleBspUartIsrRx((uint8_t)(i & 0xFF));
    }

    /* 257th byte – must be dropped, must NOT write past end of array */
    HandleBspUartIsrRx(0xFF);

    TEST_ASSERT_TRUE(IsBspUartOverflow());
    TEST_ASSERT_EQUAL_UINT16(BSP_UART_RX_RING_BUF_SIZE, GetBspUartAvailable());

    /* Drain the buffer and verify nRead is exactly 256, not a corrupted value */
    uint8_t  dataBuf[BSP_UART_RX_RING_BUF_SIZE];
    uint16_t nRead = 0;
    ReadBspUart(dataBuf, BSP_UART_RX_RING_BUF_SIZE, &nRead);
    TEST_ASSERT_EQUAL_UINT16(BSP_UART_RX_RING_BUF_SIZE, nRead);
}

/*
 * Test case: 3.6
 * IsBspUartOverflow() must clear its flag automatically after the first call
 * that returns true, so the second call returns false.
 *
 * Why: without auto-clear the caller cannot distinguish a new overflow event
 * from a stale one – every subsequent poll would return true forever.
 * One overflow event must produce exactly one true return, then reset,
 * so that UART_Task sends NACK exactly once per overflow, not continuously.
 */
void TestHandleIsrRxOverflowFlagClearsAfterCheck(void)
{
    for (uint16_t i = 0; i <= BSP_UART_RX_RING_BUF_SIZE; i++) {
        HandleBspUartIsrRx(0xAB);
    }

    TEST_ASSERT_TRUE(IsBspUartOverflow());    /* first call  – flag is set   */
    TEST_ASSERT_FALSE(IsBspUartOverflow());   /* second call – flag cleared  */
}

/*
 * Test case: 3.7
 * Ring buffer wrap-around: push 200 bytes, read them, then push 100 more.
 * The head/tail indices wrap around internally; data must still be correct.
 */
void TestHandleIsrRxRingBufferWrapsAround(void)
{
    /* ── First batch: push and drain 200 bytes ───────── */
    for (uint8_t i = 0; i < 200; i++) {
        HandleBspUartIsrRx((uint8_t)(i + 1));   /* start from 1, avoid 0x00 sentinel */
    }

    uint8_t  discard[200];
    uint16_t nRead = 0;
    ReadBspUart(discard, 200, &nRead);
    TEST_ASSERT_EQUAL_UINT16(200, nRead);

    /* ── Second batch: 100 bytes after wrap-around ────── */
    for (uint8_t i = 0; i < 100; i++) {
        HandleBspUartIsrRx((uint8_t)(i + 100));
    }

    TEST_ASSERT_EQUAL_UINT16(100, GetBspUartAvailable());

    uint8_t buf[100];
    ReadBspUart(buf, 100, &nRead);
    TEST_ASSERT_EQUAL_UINT16(100, nRead);

    for (uint8_t i = 0; i < 100; i++) {
        TEST_ASSERT_EQUAL_HEX8((uint8_t)(i + 100), buf[i]);
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 4 – ReadBspUart()
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 4.1
 * Reading from an empty ring buffer must return BSP_UART_ERR_NO_DATA
 * and set outRead to 0.
 */
void TestReadBspUartEmptyBufferReturnsNoData(void)
{
    uint8_t  buf[4] = {0};
    uint16_t nRead  = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 4, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NO_DATA, ret);
    TEST_ASSERT_EQUAL_UINT16(0, nRead);
}

/*
 * Test case: 4.2
 * Requesting more bytes than available must read only the available count,
 * set outRead to the actual count, and return BSP_UART_OK.
 */
void TestReadBspUartReadsOnlyAvailableBytes(void)
{
    HandleBspUartIsrRx(0x11);
    HandleBspUartIsrRx(0x22);

    uint8_t  buf[10] = {0};
    uint16_t nRead   = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 10, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(2,    nRead);
    TEST_ASSERT_EQUAL_HEX8(0x11,  buf[0]);
    TEST_ASSERT_EQUAL_HEX8(0x22,  buf[1]);

    /* Available must be 0 after draining all bytes, not wrapped uint16 */
    TEST_ASSERT_EQUAL_UINT16(0, GetBspUartAvailable());
}

/*
 * Test case: 4.3
 * Passing a NULL output buffer must return BSP_UART_ERR_NULL_PTR.
 */
void TestReadBspUartNullBufferReturnsError(void)
{
    HandleBspUartIsrRx(0xAB);

    uint16_t        nRead = 0;
    BspUartStatus_t ret   = ReadBspUart(NULL, 1, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NULL_PTR, ret);
}

/*
 * Test case: 4.4
 * After reading N bytes, GetBspUartAvailable() must decrease by exactly N.
 */
void TestReadBspUartDecreasesAvailableCount(void)
{
    HandleBspUartIsrRx(0x01);
    HandleBspUartIsrRx(0x02);
    HandleBspUartIsrRx(0x03);
    HandleBspUartIsrRx(0x04);

    TEST_ASSERT_EQUAL_UINT16(4, GetBspUartAvailable());

    uint8_t  buf[2];
    uint16_t nRead = 0;
    ReadBspUart(buf, 2, &nRead);

    TEST_ASSERT_EQUAL_UINT16(2, GetBspUartAvailable());
}

/*
 * Test case: 4.5
 * When len < available, outRead must equal the number of bytes actually read
 * (len), not the total bytes available in the buffer.
 */
void TestReadBspUartPartialReadReportsActualCount(void)
{
    HandleBspUartIsrRx(0x01);
    HandleBspUartIsrRx(0x02);
    HandleBspUartIsrRx(0x03);
    HandleBspUartIsrRx(0x04);

    uint8_t  buf[2];
    uint16_t nRead = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 2, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(2, nRead);   /* must be 2, not 4 */
}

/*
 * Test case: 4.6
 * Two sequential partial reads must each return the correct next bytes,
 * not the same stale bytes from the start of the buffer.
 *
 * This exposes a fundamental FIFO violation: after a partial read of N bytes
 * the implementation does not advance a read-head pointer – it always reads
 * from mDataBuffer[0].  A second read therefore returns the same N bytes
 * again instead of the next N bytes in the queue.
 * Fix: introduce separate head and tail indices (proper ring buffer) so that
 * each read advances the head by the number of bytes consumed.
 */
void TestReadBspUartSequentialPartialReadsReturnCorrectData(void)
{
    HandleBspUartIsrRx(0x01);
    HandleBspUartIsrRx(0x02);
    HandleBspUartIsrRx(0x03);
    HandleBspUartIsrRx(0x04);

    /* ── First read: consume bytes 1 and 2 ──────────── */
    uint8_t  buf1[2];
    uint16_t nRead1 = 0;
    ReadBspUart(buf1, 2, &nRead1);
    TEST_ASSERT_EQUAL_UINT16(2,    nRead1);
    TEST_ASSERT_EQUAL_HEX8(0x01,  buf1[0]);
    TEST_ASSERT_EQUAL_HEX8(0x02,  buf1[1]);

    /* ── Second read: must return bytes 3 and 4, not 1 and 2 again ── */
    uint8_t  buf2[2];
    uint16_t nRead2 = 0;
    BspUartStatus_t ret = ReadBspUart(buf2, 2, &nRead2);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(2,    nRead2);
    TEST_ASSERT_EQUAL_HEX8(0x03,  buf2[0]);
    TEST_ASSERT_EQUAL_HEX8(0x04,  buf2[1]);
}

/*
 * Test case: 4.7
 * After draining all bytes from the buffer, a subsequent ReadBspUart()
 * must return BSP_UART_ERR_NO_DATA, not BSP_UART_OK with nRead = 0.
 *
 * This exposes a bug in the empty-detection logic: IsBufferEmpty() scans
 * mDataBuffer for any non-zero byte to decide if data is present.  After
 * a complete drain, mCurrentNumberOfBytes = 0 but the buffer still holds
 * the old (non-zero) bytes that were read – they are never zeroed out on
 * read.  IsBufferEmpty() therefore finds non-zero bytes and returns 1
 * (not empty), so !IsBufferEmpty() = 0, the condition evaluates to false,
 * and ReadBspUart() skips the ERR_NO_DATA guard entirely.  The while loop
 * then runs 0 iterations and returns BSP_UART_OK with out_read = 0.
 * Fix: replace IsBufferEmpty() with a simple counter check:
 *   if (mCurrentNumberOfBytes == 0) → return ERR_NO_DATA.
 */
void TestReadBspUartAfterDrainReturnsNoData(void)
{
    HandleBspUartIsrRx(0xAA);
    HandleBspUartIsrRx(0xBB);

    /* Drain all bytes */
    uint8_t  drain[2];
    uint16_t nRead = 0;
    ReadBspUart(drain, 2, &nRead);
    TEST_ASSERT_EQUAL_UINT16(2, nRead);

    /* Buffer is now logically empty – mCurrentNumberOfBytes = 0.
     * Old data still sits in mDataBuffer[0..1].
     * Must return ERR_NO_DATA, NOT OK with nRead = 0. */
    uint8_t  buf[2];
    nRead = 0;
    BspUartStatus_t ret = ReadBspUart(buf, 2, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NO_DATA, ret);
    TEST_ASSERT_EQUAL_UINT16(0, nRead);
}