/*
 * TestUART.c
 *
 * Unit tests for the BspUart layer – STM32 <-> ESP32C3
 * Updated: May 02, 2026
 *
 */

#include "unity.h"
#include "UartCommon.h"
#include "Mockstm32f1xx_hal_uart.h"   /* CMock generated */

#include <string.h>

/* ── Fixtures ────────────────────────────────────────────────────────────── */

/*
 * Dummy handle that represents the handle MX_USART1_UART_Init() would
 * have filled in main.c.  Its contents do not matter for BSP tests –
 * only the pointer identity is relevant.
 */
static UART_HandleTypeDef sDummyHandle;

/* ── setUp / tearDown ───────────────────────────────────────────────────── */

void setUp(void)
{
    ResetBspUartState();
}

void tearDown(void)
{
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 1 – InitBspUart()
 *
 * MX_USART1_UART_Init() is generated by CubeMX and called in main.c before
 * any BSP function.  InitBspUart() therefore does NOT call HAL_UART_Init()
 * again – it only stores the already-initialised handle and sets the ready
 * flag.  No HAL mock is needed in this suite.
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 1.1
 * InitBspUart() with a valid handle must return BSP_UART_OK.
 * No HAL function should be called.
 */
void TestInitBspUartWithValidHandleReturnsOk(void)
{
    BspUartStatus_t ret = InitBspUart(&sDummyHandle);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
}

/*
 * Test case: 1.2
 * InitBspUart() with a NULL handle must return BSP_UART_ERR_NULL_PTR.
 * No HAL function should be called.
 */
void TestInitBspUartNullHandleReturnsError(void)
{
    BspUartStatus_t ret = InitBspUart(NULL);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NULL_PTR, ret);
}

/*
 * Test case: 1.3
 * Calling SendBspUart() before InitBspUart() must return BSP_UART_ERR_NOT_INIT.
 * ResetBspUartState() in setUp guarantees the init flag is cleared.
 */
void TestSendBspUartBeforeInitReturnsNotInit(void)
{
    uint8_t         data[] = {0x01, 0x02};
    BspUartStatus_t ret    = SendBspUart(&sDummyHandle, data, 2);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NOT_INIT, ret);
}

/*
 * Test case: 1.4
 * After a successful InitBspUart(), calling ResetBspUartState() and then
 * SendBspUart() must still return BSP_UART_ERR_NOT_INIT.
 *
 * This test exposes the missing init flag: if ResetBspUartState() does not
 * clear a dedicated mIsInitialized field, mCurrentStatus stays BSP_UART_OK
 * after reset and SendBspUart() skips the NOT_INIT guard entirely.
 */
void TestSendBspUartAfterResetReturnsNotInit(void)
{
    InitBspUart(&sDummyHandle);   /* mCurrentStatus = BSP_UART_OK */
    ResetBspUartState();          /* must also clear the init flag */

    uint8_t         data[] = {0x01, 0x02};
    BspUartStatus_t ret    = SendBspUart(&sDummyHandle, data, 2);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NOT_INIT, ret);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 2 – SendBspUart()
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 2.1
 * SendBspUart() must call HAL_UART_Transmit with the correct buffer and
 * length, and return BSP_UART_OK when HAL succeeds.
 */
void TestSendBspUartCallsHalTransmit(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0xAA, 0x01, 0x02, 0x55};

    HAL_UART_Transmit_ExpectAndReturn(
        &sDummyHandle, data, 4, BSP_UART_TX_TIMEOUT_MS, HAL_OK);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, data, 4);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
}

/*
 * Test case: 2.2
 * When HAL_UART_Transmit returns HAL_ERROR, SendBspUart() must return
 * BSP_UART_ERR_HAL.
 */
void TestSendBspUartHalErrorReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0x01};
    HAL_UART_Transmit_IgnoreAndReturn(HAL_ERROR);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, data, 1);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_HAL, ret);
}

/*
 * Test case: 2.3
 * Passing a NULL data pointer must return BSP_UART_ERR_NULL_PTR.
 * HAL_UART_Transmit must not be called.
 */
void TestSendBspUartNullPointerReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, NULL, 4);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NULL_PTR, ret);
}

/*
 * Test case: 2.4
 * Passing len = 0 must return BSP_UART_ERR_ZERO_LEN.
 * HAL_UART_Transmit must not be called.
 */
void TestSendBspUartZeroLenReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t         data[] = {0x01};
    BspUartStatus_t ret    = SendBspUart(&sDummyHandle, data, 0);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_ZERO_LEN, ret);
}

/*
 * Test case: 2.5
 * When HAL_UART_Transmit returns HAL_BUSY, SendBspUart() must return
 * BSP_UART_ERR_HAL.  Retry logic is not handled at this layer.
 */
void TestSendBspUartHalBusyReturnsError(void)
{
    InitBspUart(&sDummyHandle);

    uint8_t data[] = {0xAB, 0xCD};
    HAL_UART_Transmit_IgnoreAndReturn(HAL_BUSY);

    BspUartStatus_t ret = SendBspUart(&sDummyHandle, data, 2);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_HAL, ret);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 3 – HandleBspUartIsrRx() → ring buffer
 *
 * ISR handler is pure logic – no HAL calls, no CMock needed.
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 3.1
 * After pushing one byte via HandleBspUartIsrRx(), GetBspUartAvailable()
 * must return 1.
 */
void TestHandleIsrRxOneByteIsAvailable(void)
{
    HandleBspUartIsrRx(0xAB);

    TEST_ASSERT_EQUAL_UINT16(1, GetBspUartAvailable());
}

/*
 * Test case: 3.2
 * After pushing N bytes, GetBspUartAvailable() must return N.
 */
void TestHandleIsrRxMultipleBytesAvailable(void)
{
    HandleBspUartIsrRx(0x01);
    HandleBspUartIsrRx(0x02);
    HandleBspUartIsrRx(0x03);

    TEST_ASSERT_EQUAL_UINT16(3, GetBspUartAvailable());
}

/*
 * Test case: 3.3
 * Bytes pushed in order must be read back in FIFO order.
 */
void TestHandleIsrRxPreservesFifoOrder(void)
{
    HandleBspUartIsrRx(0xAA);
    HandleBspUartIsrRx(0xBB);
    HandleBspUartIsrRx(0xCC);

    uint8_t  buf[3] = {0};
    uint16_t nRead  = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 3, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(3,    nRead);
    TEST_ASSERT_EQUAL_HEX8(0xAA,  buf[0]);
    TEST_ASSERT_EQUAL_HEX8(0xBB,  buf[1]);
    TEST_ASSERT_EQUAL_HEX8(0xCC,  buf[2]);
}

/*
 * Test case: 3.4
 * Pushing a 0x00 byte must be readable as valid data, not treated as empty.
 *
 * BUG FOUND: IsBufferEmpty() scans for any byte != 0 to detect data.
 * A payload of 0x00 is a valid UART byte (e.g. CMD_ACK in our protocol).
 * With the current zero-sentinel approach, ReadBspUart() returns
 * BSP_UART_ERR_NO_DATA even though 1 byte is available.
 * Fix: replace IsBufferEmpty() with a counter-based check
 * (mCurrentNumberOfBytes == 0), removing the zero-sentinel entirely.
 */
void TestHandleIsrRxZeroBytePayloadIsReadable(void)
{
    HandleBspUartIsrRx(0x00);

    TEST_ASSERT_EQUAL_UINT16(1, GetBspUartAvailable());

    uint8_t  buf[1] = {0xFF};   /* pre-fill to detect non-write */
    uint16_t nRead  = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 1, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(1,    nRead);
    TEST_ASSERT_EQUAL_HEX8(0x00,  buf[0]);
}

/*
 * Test case: 3.5
 * When the ring buffer is full (256 bytes), the next byte pushed must be
 * dropped and IsBspUartOverflow() must return true.
 * The 256 bytes already in the buffer must be preserved.
 */
void TestHandleIsrRxOverflowSetsFlag(void)
{
    for (uint16_t i = 0; i < BSP_UART_RX_RING_BUF_SIZE; i++) {
        HandleBspUartIsrRx((uint8_t)(i & 0xFF));
    }

    /* 257th byte – must be dropped */
    HandleBspUartIsrRx(0xFF);

    TEST_ASSERT_TRUE(IsBspUartOverflow());
    TEST_ASSERT_EQUAL_UINT16(BSP_UART_RX_RING_BUF_SIZE, GetBspUartAvailable());
}

/*
 * Test case: 3.6
 * IsBspUartOverflow() must clear its flag automatically after the first call
 * that returns true, so the second call returns false.
 *
 * Why: without auto-clear the caller cannot distinguish a new overflow event
 * from a stale one – every subsequent poll would return true forever.
 * One overflow event must produce exactly one true return, then reset,
 * so that UART_Task sends NACK exactly once per overflow, not continuously.
 *
 * BUG FOUND: current IsBspUartOverflow() sets mOverflowFlag = 1 but never
 * clears it, so the second call also returns true.
 * Fix: reset mOverflowFlag to 0 before returning 1.
 */
void TestHandleIsrRxOverflowFlagClearsAfterCheck(void)
{
    for (uint16_t i = 0; i <= BSP_UART_RX_RING_BUF_SIZE; i++) {
        HandleBspUartIsrRx(0xAB);
    }

    TEST_ASSERT_TRUE(IsBspUartOverflow());    /* first call  – flag is set   */
    TEST_ASSERT_FALSE(IsBspUartOverflow());   /* second call – flag cleared  */
}

/*
 * Test case: 3.7
 * Ring buffer wrap-around: push 200 bytes, read them, then push 100 more.
 * The head/tail indices wrap around internally; data must still be correct.
 */
void TestHandleIsrRxRingBufferWrapsAround(void)
{
    /* ── First batch: push and drain 200 bytes ───────── */
    for (uint8_t i = 0; i < 200; i++) {
        HandleBspUartIsrRx((uint8_t)(i + 1));   /* start from 1, avoid 0x00 sentinel */
    }

    uint8_t  discard[200];
    uint16_t nRead = 0;
    ReadBspUart(discard, 200, &nRead);
    TEST_ASSERT_EQUAL_UINT16(200, nRead);

    /* ── Second batch: 100 bytes after wrap-around ────── */
    for (uint8_t i = 0; i < 100; i++) {
        HandleBspUartIsrRx((uint8_t)(i + 100));
    }

    TEST_ASSERT_EQUAL_UINT16(100, GetBspUartAvailable());

    uint8_t buf[100];
    ReadBspUart(buf, 100, &nRead);
    TEST_ASSERT_EQUAL_UINT16(100, nRead);

    for (uint8_t i = 0; i < 100; i++) {
        TEST_ASSERT_EQUAL_HEX8((uint8_t)(i + 100), buf[i]);
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SUITE 4 – ReadBspUart()
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * Test case: 4.1
 * Reading from an empty ring buffer must return BSP_UART_ERR_NO_DATA
 * and set outRead to 0.
 */
void TestReadBspUartEmptyBufferReturnsNoData(void)
{
    uint8_t  buf[4] = {0};
    uint16_t nRead  = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 4, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NO_DATA, ret);
    TEST_ASSERT_EQUAL_UINT16(0, nRead);
}

/*
 * Test case: 4.2
 * Requesting more bytes than available must read only the available count,
 * set outRead to the actual count, and return BSP_UART_OK.
 *
 * BUG FOUND: the current loop runs len times unconditionally, which causes
 * mCurrentNumberOfBytes (uint16_t) to underflow-wrap when len > available.
 * Fix: cap the loop at min(len, mCurrentNumberOfBytes).
 */
void TestReadBspUartReadsOnlyAvailableBytes(void)
{
    HandleBspUartIsrRx(0x11);
    HandleBspUartIsrRx(0x22);

    uint8_t  buf[10] = {0};
    uint16_t nRead   = 0;

    BspUartStatus_t ret = ReadBspUart(buf, 10, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_OK, ret);
    TEST_ASSERT_EQUAL_UINT16(2,    nRead);
    TEST_ASSERT_EQUAL_HEX8(0x11,  buf[0]);
    TEST_ASSERT_EQUAL_HEX8(0x22,  buf[1]);

    /* Available must be 0 after draining all bytes, not wrapped uint16 */
    TEST_ASSERT_EQUAL_UINT16(0, GetBspUartAvailable());
}

/*
 * Test case: 4.3
 * Passing a NULL output buffer must return BSP_UART_ERR_NULL_PTR.
 */
void TestReadBspUartNullBufferReturnsError(void)
{
    HandleBspUartIsrRx(0xAB);

    uint16_t        nRead = 0;
    BspUartStatus_t ret   = ReadBspUart(NULL, 1, &nRead);

    TEST_ASSERT_EQUAL(BSP_UART_ERR_NULL_PTR, ret);
}

/*
 * Test case: 4.4
 * After reading N bytes, GetBspUartAvailable() must decrease by exactly N.
 */
void TestReadBspUartDecreasesAvailableCount(void)
{
    HandleBspUartIsrRx(0x01);
    HandleBspUartIsrRx(0x02);
    HandleBspUartIsrRx(0x03);
    HandleBspUartIsrRx(0x04);

    TEST_ASSERT_EQUAL_UINT16(4, GetBspUartAvailable());

    uint8_t  buf[2];
    uint16_t nRead = 0;
    ReadBspUart(buf, 2, &nRead);

    TEST_ASSERT_EQUAL_UINT16(2, GetBspUartAvailable());
}