/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTM32F1XX_HAL_UART_H
#define _MOCKSTM32F1XX_HAL_UART_H

#include "unity.h"
#include "stm32f1xx_hal_uart.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockstm32f1xx_hal_uart_Init(void);
void Mockstm32f1xx_hal_uart_Destroy(void);
void Mockstm32f1xx_hal_uart_Verify(void);




#define HAL_UART_Init_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Init requires _IgnoreAndReturn");
#define HAL_UART_Init_IgnoreAndReturn(cmock_retval) HAL_UART_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Init_StopIgnore() HAL_UART_Init_CMockStopIgnore()
void HAL_UART_Init_CMockStopIgnore(void);
#define HAL_UART_Init_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_Init requires _ExpectAndReturn");
#define HAL_UART_Init_ExpectAndReturn(huart, cmock_retval) HAL_UART_Init_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_Init_Ignore() TEST_FAIL_MESSAGE("HAL_HalfDuplex_Init requires _IgnoreAndReturn");
#define HAL_HalfDuplex_Init_IgnoreAndReturn(cmock_retval) HAL_HalfDuplex_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_HalfDuplex_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_Init_StopIgnore() HAL_HalfDuplex_Init_CMockStopIgnore()
void HAL_HalfDuplex_Init_CMockStopIgnore(void);
#define HAL_HalfDuplex_Init_Expect(huart) TEST_FAIL_MESSAGE("HAL_HalfDuplex_Init requires _ExpectAndReturn");
#define HAL_HalfDuplex_Init_ExpectAndReturn(huart, cmock_retval) HAL_HalfDuplex_Init_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_HalfDuplex_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_LIN_Init_Ignore() TEST_FAIL_MESSAGE("HAL_LIN_Init requires _IgnoreAndReturn");
#define HAL_LIN_Init_IgnoreAndReturn(cmock_retval) HAL_LIN_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_LIN_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_LIN_Init_StopIgnore() HAL_LIN_Init_CMockStopIgnore()
void HAL_LIN_Init_CMockStopIgnore(void);
#define HAL_LIN_Init_Expect(huart, BreakDetectLength) TEST_FAIL_MESSAGE("HAL_LIN_Init requires _ExpectAndReturn");
#define HAL_LIN_Init_ExpectAndReturn(huart, BreakDetectLength, cmock_retval) HAL_LIN_Init_CMockExpectAndReturn(__LINE__, huart, BreakDetectLength, cmock_retval)
void HAL_LIN_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint32_t BreakDetectLength, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_Init_Ignore() TEST_FAIL_MESSAGE("HAL_MultiProcessor_Init requires _IgnoreAndReturn");
#define HAL_MultiProcessor_Init_IgnoreAndReturn(cmock_retval) HAL_MultiProcessor_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_MultiProcessor_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_Init_StopIgnore() HAL_MultiProcessor_Init_CMockStopIgnore()
void HAL_MultiProcessor_Init_CMockStopIgnore(void);
#define HAL_MultiProcessor_Init_Expect(huart, Address, WakeUpMethod) TEST_FAIL_MESSAGE("HAL_MultiProcessor_Init requires _ExpectAndReturn");
#define HAL_MultiProcessor_Init_ExpectAndReturn(huart, Address, WakeUpMethod, cmock_retval) HAL_MultiProcessor_Init_CMockExpectAndReturn(__LINE__, huart, Address, WakeUpMethod, cmock_retval)
void HAL_MultiProcessor_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t Address, uint32_t WakeUpMethod, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DeInit_Ignore() TEST_FAIL_MESSAGE("HAL_UART_DeInit requires _IgnoreAndReturn");
#define HAL_UART_DeInit_IgnoreAndReturn(cmock_retval) HAL_UART_DeInit_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_DeInit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DeInit_StopIgnore() HAL_UART_DeInit_CMockStopIgnore()
void HAL_UART_DeInit_CMockStopIgnore(void);
#define HAL_UART_DeInit_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_DeInit requires _ExpectAndReturn");
#define HAL_UART_DeInit_ExpectAndReturn(huart, cmock_retval) HAL_UART_DeInit_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_MspInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_MspInit requires _Ignore (not AndReturn)");
#define HAL_UART_MspInit_Ignore() HAL_UART_MspInit_CMockIgnore()
void HAL_UART_MspInit_CMockIgnore(void);
#define HAL_UART_MspInit_StopIgnore() HAL_UART_MspInit_CMockStopIgnore()
void HAL_UART_MspInit_CMockStopIgnore(void);
#define HAL_UART_MspInit_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_MspInit requires _Expect (not AndReturn)");
#define HAL_UART_MspInit_Expect(huart) HAL_UART_MspInit_CMockExpect(__LINE__, huart)
void HAL_UART_MspInit_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_MspDeInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_MspDeInit requires _Ignore (not AndReturn)");
#define HAL_UART_MspDeInit_Ignore() HAL_UART_MspDeInit_CMockIgnore()
void HAL_UART_MspDeInit_CMockIgnore(void);
#define HAL_UART_MspDeInit_StopIgnore() HAL_UART_MspDeInit_CMockStopIgnore()
void HAL_UART_MspDeInit_CMockStopIgnore(void);
#define HAL_UART_MspDeInit_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_MspDeInit requires _Expect (not AndReturn)");
#define HAL_UART_MspDeInit_Expect(huart) HAL_UART_MspDeInit_CMockExpect(__LINE__, huart)
void HAL_UART_MspDeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_RegisterCallback_Ignore() TEST_FAIL_MESSAGE("HAL_UART_RegisterCallback requires _IgnoreAndReturn");
#define HAL_UART_RegisterCallback_IgnoreAndReturn(cmock_retval) HAL_UART_RegisterCallback_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_RegisterCallback_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_RegisterCallback_StopIgnore() HAL_UART_RegisterCallback_CMockStopIgnore()
void HAL_UART_RegisterCallback_CMockStopIgnore(void);
#define HAL_UART_RegisterCallback_Expect(huart, CallbackID, pCallback) TEST_FAIL_MESSAGE("HAL_UART_RegisterCallback requires _ExpectAndReturn");
#define HAL_UART_RegisterCallback_ExpectAndReturn(huart, CallbackID, pCallback, cmock_retval) HAL_UART_RegisterCallback_CMockExpectAndReturn(__LINE__, huart, CallbackID, pCallback, cmock_retval)
void HAL_UART_RegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_UART_CallbackIDTypeDef CallbackID, pUART_CallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_UnRegisterCallback_Ignore() TEST_FAIL_MESSAGE("HAL_UART_UnRegisterCallback requires _IgnoreAndReturn");
#define HAL_UART_UnRegisterCallback_IgnoreAndReturn(cmock_retval) HAL_UART_UnRegisterCallback_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_UnRegisterCallback_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_UnRegisterCallback_StopIgnore() HAL_UART_UnRegisterCallback_CMockStopIgnore()
void HAL_UART_UnRegisterCallback_CMockStopIgnore(void);
#define HAL_UART_UnRegisterCallback_Expect(huart, CallbackID) TEST_FAIL_MESSAGE("HAL_UART_UnRegisterCallback requires _ExpectAndReturn");
#define HAL_UART_UnRegisterCallback_ExpectAndReturn(huart, CallbackID, cmock_retval) HAL_UART_UnRegisterCallback_CMockExpectAndReturn(__LINE__, huart, CallbackID, cmock_retval)
void HAL_UART_UnRegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_UART_CallbackIDTypeDef CallbackID, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_RegisterRxEventCallback_Ignore() TEST_FAIL_MESSAGE("HAL_UART_RegisterRxEventCallback requires _IgnoreAndReturn");
#define HAL_UART_RegisterRxEventCallback_IgnoreAndReturn(cmock_retval) HAL_UART_RegisterRxEventCallback_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_RegisterRxEventCallback_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_RegisterRxEventCallback_StopIgnore() HAL_UART_RegisterRxEventCallback_CMockStopIgnore()
void HAL_UART_RegisterRxEventCallback_CMockStopIgnore(void);
#define HAL_UART_RegisterRxEventCallback_Expect(huart, pCallback) TEST_FAIL_MESSAGE("HAL_UART_RegisterRxEventCallback requires _ExpectAndReturn");
#define HAL_UART_RegisterRxEventCallback_ExpectAndReturn(huart, pCallback, cmock_retval) HAL_UART_RegisterRxEventCallback_CMockExpectAndReturn(__LINE__, huart, pCallback, cmock_retval)
void HAL_UART_RegisterRxEventCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, pUART_RxEventCallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_UnRegisterRxEventCallback_Ignore() TEST_FAIL_MESSAGE("HAL_UART_UnRegisterRxEventCallback requires _IgnoreAndReturn");
#define HAL_UART_UnRegisterRxEventCallback_IgnoreAndReturn(cmock_retval) HAL_UART_UnRegisterRxEventCallback_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_UnRegisterRxEventCallback_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_UnRegisterRxEventCallback_StopIgnore() HAL_UART_UnRegisterRxEventCallback_CMockStopIgnore()
void HAL_UART_UnRegisterRxEventCallback_CMockStopIgnore(void);
#define HAL_UART_UnRegisterRxEventCallback_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_UnRegisterRxEventCallback requires _ExpectAndReturn");
#define HAL_UART_UnRegisterRxEventCallback_ExpectAndReturn(huart, cmock_retval) HAL_UART_UnRegisterRxEventCallback_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_UnRegisterRxEventCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Transmit requires _IgnoreAndReturn");
#define HAL_UART_Transmit_IgnoreAndReturn(cmock_retval) HAL_UART_Transmit_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Transmit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_StopIgnore() HAL_UART_Transmit_CMockStopIgnore()
void HAL_UART_Transmit_CMockStopIgnore(void);
#define HAL_UART_Transmit_Expect(huart, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_UART_Transmit requires _ExpectAndReturn");
#define HAL_UART_Transmit_ExpectAndReturn(huart, pData, Size, Timeout, cmock_retval) HAL_UART_Transmit_CMockExpectAndReturn(__LINE__, huart, pData, Size, Timeout, cmock_retval)
void HAL_UART_Transmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, const uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Receive requires _IgnoreAndReturn");
#define HAL_UART_Receive_IgnoreAndReturn(cmock_retval) HAL_UART_Receive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Receive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_StopIgnore() HAL_UART_Receive_CMockStopIgnore()
void HAL_UART_Receive_CMockStopIgnore(void);
#define HAL_UART_Receive_Expect(huart, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_UART_Receive requires _ExpectAndReturn");
#define HAL_UART_Receive_ExpectAndReturn(huart, pData, Size, Timeout, cmock_retval) HAL_UART_Receive_CMockExpectAndReturn(__LINE__, huart, pData, Size, Timeout, cmock_retval)
void HAL_UART_Receive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_IT_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Transmit_IT requires _IgnoreAndReturn");
#define HAL_UART_Transmit_IT_IgnoreAndReturn(cmock_retval) HAL_UART_Transmit_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Transmit_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_IT_StopIgnore() HAL_UART_Transmit_IT_CMockStopIgnore()
void HAL_UART_Transmit_IT_CMockStopIgnore(void);
#define HAL_UART_Transmit_IT_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("HAL_UART_Transmit_IT requires _ExpectAndReturn");
#define HAL_UART_Transmit_IT_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Transmit_IT_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, const uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_IT_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Receive_IT requires _IgnoreAndReturn");
#define HAL_UART_Receive_IT_IgnoreAndReturn(cmock_retval) HAL_UART_Receive_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Receive_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_IT_StopIgnore() HAL_UART_Receive_IT_CMockStopIgnore()
void HAL_UART_Receive_IT_CMockStopIgnore(void);
#define HAL_UART_Receive_IT_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("HAL_UART_Receive_IT requires _ExpectAndReturn");
#define HAL_UART_Receive_IT_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Receive_IT_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_DMA_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Transmit_DMA requires _IgnoreAndReturn");
#define HAL_UART_Transmit_DMA_IgnoreAndReturn(cmock_retval) HAL_UART_Transmit_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Transmit_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_DMA_StopIgnore() HAL_UART_Transmit_DMA_CMockStopIgnore()
void HAL_UART_Transmit_DMA_CMockStopIgnore(void);
#define HAL_UART_Transmit_DMA_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("HAL_UART_Transmit_DMA requires _ExpectAndReturn");
#define HAL_UART_Transmit_DMA_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Transmit_DMA_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, const uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_DMA_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Receive_DMA requires _IgnoreAndReturn");
#define HAL_UART_Receive_DMA_IgnoreAndReturn(cmock_retval) HAL_UART_Receive_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Receive_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_DMA_StopIgnore() HAL_UART_Receive_DMA_CMockStopIgnore()
void HAL_UART_Receive_DMA_CMockStopIgnore(void);
#define HAL_UART_Receive_DMA_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("HAL_UART_Receive_DMA requires _ExpectAndReturn");
#define HAL_UART_Receive_DMA_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Receive_DMA_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAPause_Ignore() TEST_FAIL_MESSAGE("HAL_UART_DMAPause requires _IgnoreAndReturn");
#define HAL_UART_DMAPause_IgnoreAndReturn(cmock_retval) HAL_UART_DMAPause_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_DMAPause_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAPause_StopIgnore() HAL_UART_DMAPause_CMockStopIgnore()
void HAL_UART_DMAPause_CMockStopIgnore(void);
#define HAL_UART_DMAPause_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_DMAPause requires _ExpectAndReturn");
#define HAL_UART_DMAPause_ExpectAndReturn(huart, cmock_retval) HAL_UART_DMAPause_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DMAPause_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAResume_Ignore() TEST_FAIL_MESSAGE("HAL_UART_DMAResume requires _IgnoreAndReturn");
#define HAL_UART_DMAResume_IgnoreAndReturn(cmock_retval) HAL_UART_DMAResume_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_DMAResume_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAResume_StopIgnore() HAL_UART_DMAResume_CMockStopIgnore()
void HAL_UART_DMAResume_CMockStopIgnore(void);
#define HAL_UART_DMAResume_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_DMAResume requires _ExpectAndReturn");
#define HAL_UART_DMAResume_ExpectAndReturn(huart, cmock_retval) HAL_UART_DMAResume_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DMAResume_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAStop_Ignore() TEST_FAIL_MESSAGE("HAL_UART_DMAStop requires _IgnoreAndReturn");
#define HAL_UART_DMAStop_IgnoreAndReturn(cmock_retval) HAL_UART_DMAStop_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_DMAStop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAStop_StopIgnore() HAL_UART_DMAStop_CMockStopIgnore()
void HAL_UART_DMAStop_CMockStopIgnore(void);
#define HAL_UART_DMAStop_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_DMAStop requires _ExpectAndReturn");
#define HAL_UART_DMAStop_ExpectAndReturn(huart, cmock_retval) HAL_UART_DMAStop_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DMAStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UARTEx_ReceiveToIdle_Ignore() TEST_FAIL_MESSAGE("HAL_UARTEx_ReceiveToIdle requires _IgnoreAndReturn");
#define HAL_UARTEx_ReceiveToIdle_IgnoreAndReturn(cmock_retval) HAL_UARTEx_ReceiveToIdle_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UARTEx_ReceiveToIdle_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UARTEx_ReceiveToIdle_StopIgnore() HAL_UARTEx_ReceiveToIdle_CMockStopIgnore()
void HAL_UARTEx_ReceiveToIdle_CMockStopIgnore(void);
#define HAL_UARTEx_ReceiveToIdle_Expect(huart, pData, Size, RxLen, Timeout) TEST_FAIL_MESSAGE("HAL_UARTEx_ReceiveToIdle requires _ExpectAndReturn");
#define HAL_UARTEx_ReceiveToIdle_ExpectAndReturn(huart, pData, Size, RxLen, Timeout, cmock_retval) HAL_UARTEx_ReceiveToIdle_CMockExpectAndReturn(__LINE__, huart, pData, Size, RxLen, Timeout, cmock_retval)
void HAL_UARTEx_ReceiveToIdle_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, uint16_t* RxLen, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_UARTEx_ReceiveToIdle_IT_Ignore() TEST_FAIL_MESSAGE("HAL_UARTEx_ReceiveToIdle_IT requires _IgnoreAndReturn");
#define HAL_UARTEx_ReceiveToIdle_IT_IgnoreAndReturn(cmock_retval) HAL_UARTEx_ReceiveToIdle_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UARTEx_ReceiveToIdle_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UARTEx_ReceiveToIdle_IT_StopIgnore() HAL_UARTEx_ReceiveToIdle_IT_CMockStopIgnore()
void HAL_UARTEx_ReceiveToIdle_IT_CMockStopIgnore(void);
#define HAL_UARTEx_ReceiveToIdle_IT_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("HAL_UARTEx_ReceiveToIdle_IT requires _ExpectAndReturn");
#define HAL_UARTEx_ReceiveToIdle_IT_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UARTEx_ReceiveToIdle_IT_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UARTEx_ReceiveToIdle_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UARTEx_ReceiveToIdle_DMA_Ignore() TEST_FAIL_MESSAGE("HAL_UARTEx_ReceiveToIdle_DMA requires _IgnoreAndReturn");
#define HAL_UARTEx_ReceiveToIdle_DMA_IgnoreAndReturn(cmock_retval) HAL_UARTEx_ReceiveToIdle_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UARTEx_ReceiveToIdle_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UARTEx_ReceiveToIdle_DMA_StopIgnore() HAL_UARTEx_ReceiveToIdle_DMA_CMockStopIgnore()
void HAL_UARTEx_ReceiveToIdle_DMA_CMockStopIgnore(void);
#define HAL_UARTEx_ReceiveToIdle_DMA_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("HAL_UARTEx_ReceiveToIdle_DMA requires _ExpectAndReturn");
#define HAL_UARTEx_ReceiveToIdle_DMA_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UARTEx_ReceiveToIdle_DMA_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UARTEx_ReceiveToIdle_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UARTEx_GetRxEventType_Ignore() TEST_FAIL_MESSAGE("HAL_UARTEx_GetRxEventType requires _IgnoreAndReturn");
#define HAL_UARTEx_GetRxEventType_IgnoreAndReturn(cmock_retval) HAL_UARTEx_GetRxEventType_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UARTEx_GetRxEventType_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_UART_RxEventTypeTypeDef cmock_to_return);
#define HAL_UARTEx_GetRxEventType_StopIgnore() HAL_UARTEx_GetRxEventType_CMockStopIgnore()
void HAL_UARTEx_GetRxEventType_CMockStopIgnore(void);
#define HAL_UARTEx_GetRxEventType_Expect(huart) TEST_FAIL_MESSAGE("HAL_UARTEx_GetRxEventType requires _ExpectAndReturn");
#define HAL_UARTEx_GetRxEventType_ExpectAndReturn(huart, cmock_retval) HAL_UARTEx_GetRxEventType_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UARTEx_GetRxEventType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_UART_RxEventTypeTypeDef cmock_to_return);
#define HAL_UART_Abort_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Abort requires _IgnoreAndReturn");
#define HAL_UART_Abort_IgnoreAndReturn(cmock_retval) HAL_UART_Abort_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Abort_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Abort_StopIgnore() HAL_UART_Abort_CMockStopIgnore()
void HAL_UART_Abort_CMockStopIgnore(void);
#define HAL_UART_Abort_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_Abort requires _ExpectAndReturn");
#define HAL_UART_Abort_ExpectAndReturn(huart, cmock_retval) HAL_UART_Abort_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_Abort_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortTransmit_Ignore() TEST_FAIL_MESSAGE("HAL_UART_AbortTransmit requires _IgnoreAndReturn");
#define HAL_UART_AbortTransmit_IgnoreAndReturn(cmock_retval) HAL_UART_AbortTransmit_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_AbortTransmit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortTransmit_StopIgnore() HAL_UART_AbortTransmit_CMockStopIgnore()
void HAL_UART_AbortTransmit_CMockStopIgnore(void);
#define HAL_UART_AbortTransmit_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_AbortTransmit requires _ExpectAndReturn");
#define HAL_UART_AbortTransmit_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortTransmit_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortTransmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortReceive_Ignore() TEST_FAIL_MESSAGE("HAL_UART_AbortReceive requires _IgnoreAndReturn");
#define HAL_UART_AbortReceive_IgnoreAndReturn(cmock_retval) HAL_UART_AbortReceive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_AbortReceive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortReceive_StopIgnore() HAL_UART_AbortReceive_CMockStopIgnore()
void HAL_UART_AbortReceive_CMockStopIgnore(void);
#define HAL_UART_AbortReceive_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_AbortReceive requires _ExpectAndReturn");
#define HAL_UART_AbortReceive_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortReceive_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortReceive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Abort_IT_Ignore() TEST_FAIL_MESSAGE("HAL_UART_Abort_IT requires _IgnoreAndReturn");
#define HAL_UART_Abort_IT_IgnoreAndReturn(cmock_retval) HAL_UART_Abort_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_Abort_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Abort_IT_StopIgnore() HAL_UART_Abort_IT_CMockStopIgnore()
void HAL_UART_Abort_IT_CMockStopIgnore(void);
#define HAL_UART_Abort_IT_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_Abort_IT requires _ExpectAndReturn");
#define HAL_UART_Abort_IT_ExpectAndReturn(huart, cmock_retval) HAL_UART_Abort_IT_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_Abort_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortTransmit_IT_Ignore() TEST_FAIL_MESSAGE("HAL_UART_AbortTransmit_IT requires _IgnoreAndReturn");
#define HAL_UART_AbortTransmit_IT_IgnoreAndReturn(cmock_retval) HAL_UART_AbortTransmit_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_AbortTransmit_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortTransmit_IT_StopIgnore() HAL_UART_AbortTransmit_IT_CMockStopIgnore()
void HAL_UART_AbortTransmit_IT_CMockStopIgnore(void);
#define HAL_UART_AbortTransmit_IT_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_AbortTransmit_IT requires _ExpectAndReturn");
#define HAL_UART_AbortTransmit_IT_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortTransmit_IT_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortTransmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortReceive_IT_Ignore() TEST_FAIL_MESSAGE("HAL_UART_AbortReceive_IT requires _IgnoreAndReturn");
#define HAL_UART_AbortReceive_IT_IgnoreAndReturn(cmock_retval) HAL_UART_AbortReceive_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_AbortReceive_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortReceive_IT_StopIgnore() HAL_UART_AbortReceive_IT_CMockStopIgnore()
void HAL_UART_AbortReceive_IT_CMockStopIgnore(void);
#define HAL_UART_AbortReceive_IT_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_AbortReceive_IT requires _ExpectAndReturn");
#define HAL_UART_AbortReceive_IT_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortReceive_IT_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortReceive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_IRQHandler_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_IRQHandler requires _Ignore (not AndReturn)");
#define HAL_UART_IRQHandler_Ignore() HAL_UART_IRQHandler_CMockIgnore()
void HAL_UART_IRQHandler_CMockIgnore(void);
#define HAL_UART_IRQHandler_StopIgnore() HAL_UART_IRQHandler_CMockStopIgnore()
void HAL_UART_IRQHandler_CMockStopIgnore(void);
#define HAL_UART_IRQHandler_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_IRQHandler requires _Expect (not AndReturn)");
#define HAL_UART_IRQHandler_Expect(huart) HAL_UART_IRQHandler_CMockExpect(__LINE__, huart)
void HAL_UART_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_TxCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_TxCpltCallback requires _Ignore (not AndReturn)");
#define HAL_UART_TxCpltCallback_Ignore() HAL_UART_TxCpltCallback_CMockIgnore()
void HAL_UART_TxCpltCallback_CMockIgnore(void);
#define HAL_UART_TxCpltCallback_StopIgnore() HAL_UART_TxCpltCallback_CMockStopIgnore()
void HAL_UART_TxCpltCallback_CMockStopIgnore(void);
#define HAL_UART_TxCpltCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_TxCpltCallback requires _Expect (not AndReturn)");
#define HAL_UART_TxCpltCallback_Expect(huart) HAL_UART_TxCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_TxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_TxHalfCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_TxHalfCpltCallback requires _Ignore (not AndReturn)");
#define HAL_UART_TxHalfCpltCallback_Ignore() HAL_UART_TxHalfCpltCallback_CMockIgnore()
void HAL_UART_TxHalfCpltCallback_CMockIgnore(void);
#define HAL_UART_TxHalfCpltCallback_StopIgnore() HAL_UART_TxHalfCpltCallback_CMockStopIgnore()
void HAL_UART_TxHalfCpltCallback_CMockStopIgnore(void);
#define HAL_UART_TxHalfCpltCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_TxHalfCpltCallback requires _Expect (not AndReturn)");
#define HAL_UART_TxHalfCpltCallback_Expect(huart) HAL_UART_TxHalfCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_TxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_RxCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_RxCpltCallback requires _Ignore (not AndReturn)");
#define HAL_UART_RxCpltCallback_Ignore() HAL_UART_RxCpltCallback_CMockIgnore()
void HAL_UART_RxCpltCallback_CMockIgnore(void);
#define HAL_UART_RxCpltCallback_StopIgnore() HAL_UART_RxCpltCallback_CMockStopIgnore()
void HAL_UART_RxCpltCallback_CMockStopIgnore(void);
#define HAL_UART_RxCpltCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_RxCpltCallback requires _Expect (not AndReturn)");
#define HAL_UART_RxCpltCallback_Expect(huart) HAL_UART_RxCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_RxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_RxHalfCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_RxHalfCpltCallback requires _Ignore (not AndReturn)");
#define HAL_UART_RxHalfCpltCallback_Ignore() HAL_UART_RxHalfCpltCallback_CMockIgnore()
void HAL_UART_RxHalfCpltCallback_CMockIgnore(void);
#define HAL_UART_RxHalfCpltCallback_StopIgnore() HAL_UART_RxHalfCpltCallback_CMockStopIgnore()
void HAL_UART_RxHalfCpltCallback_CMockStopIgnore(void);
#define HAL_UART_RxHalfCpltCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_RxHalfCpltCallback requires _Expect (not AndReturn)");
#define HAL_UART_RxHalfCpltCallback_Expect(huart) HAL_UART_RxHalfCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_RxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_ErrorCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_ErrorCallback requires _Ignore (not AndReturn)");
#define HAL_UART_ErrorCallback_Ignore() HAL_UART_ErrorCallback_CMockIgnore()
void HAL_UART_ErrorCallback_CMockIgnore(void);
#define HAL_UART_ErrorCallback_StopIgnore() HAL_UART_ErrorCallback_CMockStopIgnore()
void HAL_UART_ErrorCallback_CMockStopIgnore(void);
#define HAL_UART_ErrorCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_ErrorCallback requires _Expect (not AndReturn)");
#define HAL_UART_ErrorCallback_Expect(huart) HAL_UART_ErrorCallback_CMockExpect(__LINE__, huart)
void HAL_UART_ErrorCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_AbortCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_AbortCpltCallback requires _Ignore (not AndReturn)");
#define HAL_UART_AbortCpltCallback_Ignore() HAL_UART_AbortCpltCallback_CMockIgnore()
void HAL_UART_AbortCpltCallback_CMockIgnore(void);
#define HAL_UART_AbortCpltCallback_StopIgnore() HAL_UART_AbortCpltCallback_CMockStopIgnore()
void HAL_UART_AbortCpltCallback_CMockStopIgnore(void);
#define HAL_UART_AbortCpltCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_AbortCpltCallback requires _Expect (not AndReturn)");
#define HAL_UART_AbortCpltCallback_Expect(huart) HAL_UART_AbortCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_AbortCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_AbortTransmitCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_AbortTransmitCpltCallback requires _Ignore (not AndReturn)");
#define HAL_UART_AbortTransmitCpltCallback_Ignore() HAL_UART_AbortTransmitCpltCallback_CMockIgnore()
void HAL_UART_AbortTransmitCpltCallback_CMockIgnore(void);
#define HAL_UART_AbortTransmitCpltCallback_StopIgnore() HAL_UART_AbortTransmitCpltCallback_CMockStopIgnore()
void HAL_UART_AbortTransmitCpltCallback_CMockStopIgnore(void);
#define HAL_UART_AbortTransmitCpltCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_AbortTransmitCpltCallback requires _Expect (not AndReturn)");
#define HAL_UART_AbortTransmitCpltCallback_Expect(huart) HAL_UART_AbortTransmitCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_AbortTransmitCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_AbortReceiveCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_AbortReceiveCpltCallback requires _Ignore (not AndReturn)");
#define HAL_UART_AbortReceiveCpltCallback_Ignore() HAL_UART_AbortReceiveCpltCallback_CMockIgnore()
void HAL_UART_AbortReceiveCpltCallback_CMockIgnore(void);
#define HAL_UART_AbortReceiveCpltCallback_StopIgnore() HAL_UART_AbortReceiveCpltCallback_CMockStopIgnore()
void HAL_UART_AbortReceiveCpltCallback_CMockStopIgnore(void);
#define HAL_UART_AbortReceiveCpltCallback_ExpectAndReturn(huart, cmock_retval) TEST_FAIL_MESSAGE("HAL_UART_AbortReceiveCpltCallback requires _Expect (not AndReturn)");
#define HAL_UART_AbortReceiveCpltCallback_Expect(huart) HAL_UART_AbortReceiveCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_AbortReceiveCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UARTEx_RxEventCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_UARTEx_RxEventCallback requires _Ignore (not AndReturn)");
#define HAL_UARTEx_RxEventCallback_Ignore() HAL_UARTEx_RxEventCallback_CMockIgnore()
void HAL_UARTEx_RxEventCallback_CMockIgnore(void);
#define HAL_UARTEx_RxEventCallback_StopIgnore() HAL_UARTEx_RxEventCallback_CMockStopIgnore()
void HAL_UARTEx_RxEventCallback_CMockStopIgnore(void);
#define HAL_UARTEx_RxEventCallback_ExpectAndReturn(huart, Size, cmock_retval) TEST_FAIL_MESSAGE("HAL_UARTEx_RxEventCallback requires _Expect (not AndReturn)");
#define HAL_UARTEx_RxEventCallback_Expect(huart, Size) HAL_UARTEx_RxEventCallback_CMockExpect(__LINE__, huart, Size)
void HAL_UARTEx_RxEventCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint16_t Size);
#define HAL_LIN_SendBreak_Ignore() TEST_FAIL_MESSAGE("HAL_LIN_SendBreak requires _IgnoreAndReturn");
#define HAL_LIN_SendBreak_IgnoreAndReturn(cmock_retval) HAL_LIN_SendBreak_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_LIN_SendBreak_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_LIN_SendBreak_StopIgnore() HAL_LIN_SendBreak_CMockStopIgnore()
void HAL_LIN_SendBreak_CMockStopIgnore(void);
#define HAL_LIN_SendBreak_Expect(huart) TEST_FAIL_MESSAGE("HAL_LIN_SendBreak requires _ExpectAndReturn");
#define HAL_LIN_SendBreak_ExpectAndReturn(huart, cmock_retval) HAL_LIN_SendBreak_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_LIN_SendBreak_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_EnterMuteMode_Ignore() TEST_FAIL_MESSAGE("HAL_MultiProcessor_EnterMuteMode requires _IgnoreAndReturn");
#define HAL_MultiProcessor_EnterMuteMode_IgnoreAndReturn(cmock_retval) HAL_MultiProcessor_EnterMuteMode_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_MultiProcessor_EnterMuteMode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_EnterMuteMode_StopIgnore() HAL_MultiProcessor_EnterMuteMode_CMockStopIgnore()
void HAL_MultiProcessor_EnterMuteMode_CMockStopIgnore(void);
#define HAL_MultiProcessor_EnterMuteMode_Expect(huart) TEST_FAIL_MESSAGE("HAL_MultiProcessor_EnterMuteMode requires _ExpectAndReturn");
#define HAL_MultiProcessor_EnterMuteMode_ExpectAndReturn(huart, cmock_retval) HAL_MultiProcessor_EnterMuteMode_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_MultiProcessor_EnterMuteMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_ExitMuteMode_Ignore() TEST_FAIL_MESSAGE("HAL_MultiProcessor_ExitMuteMode requires _IgnoreAndReturn");
#define HAL_MultiProcessor_ExitMuteMode_IgnoreAndReturn(cmock_retval) HAL_MultiProcessor_ExitMuteMode_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_MultiProcessor_ExitMuteMode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_ExitMuteMode_StopIgnore() HAL_MultiProcessor_ExitMuteMode_CMockStopIgnore()
void HAL_MultiProcessor_ExitMuteMode_CMockStopIgnore(void);
#define HAL_MultiProcessor_ExitMuteMode_Expect(huart) TEST_FAIL_MESSAGE("HAL_MultiProcessor_ExitMuteMode requires _ExpectAndReturn");
#define HAL_MultiProcessor_ExitMuteMode_ExpectAndReturn(huart, cmock_retval) HAL_MultiProcessor_ExitMuteMode_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_MultiProcessor_ExitMuteMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_EnableTransmitter_Ignore() TEST_FAIL_MESSAGE("HAL_HalfDuplex_EnableTransmitter requires _IgnoreAndReturn");
#define HAL_HalfDuplex_EnableTransmitter_IgnoreAndReturn(cmock_retval) HAL_HalfDuplex_EnableTransmitter_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_HalfDuplex_EnableTransmitter_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_EnableTransmitter_StopIgnore() HAL_HalfDuplex_EnableTransmitter_CMockStopIgnore()
void HAL_HalfDuplex_EnableTransmitter_CMockStopIgnore(void);
#define HAL_HalfDuplex_EnableTransmitter_Expect(huart) TEST_FAIL_MESSAGE("HAL_HalfDuplex_EnableTransmitter requires _ExpectAndReturn");
#define HAL_HalfDuplex_EnableTransmitter_ExpectAndReturn(huart, cmock_retval) HAL_HalfDuplex_EnableTransmitter_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_HalfDuplex_EnableTransmitter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_EnableReceiver_Ignore() TEST_FAIL_MESSAGE("HAL_HalfDuplex_EnableReceiver requires _IgnoreAndReturn");
#define HAL_HalfDuplex_EnableReceiver_IgnoreAndReturn(cmock_retval) HAL_HalfDuplex_EnableReceiver_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_HalfDuplex_EnableReceiver_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_EnableReceiver_StopIgnore() HAL_HalfDuplex_EnableReceiver_CMockStopIgnore()
void HAL_HalfDuplex_EnableReceiver_CMockStopIgnore(void);
#define HAL_HalfDuplex_EnableReceiver_Expect(huart) TEST_FAIL_MESSAGE("HAL_HalfDuplex_EnableReceiver requires _ExpectAndReturn");
#define HAL_HalfDuplex_EnableReceiver_ExpectAndReturn(huart, cmock_retval) HAL_HalfDuplex_EnableReceiver_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_HalfDuplex_EnableReceiver_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_GetState_Ignore() TEST_FAIL_MESSAGE("HAL_UART_GetState requires _IgnoreAndReturn");
#define HAL_UART_GetState_IgnoreAndReturn(cmock_retval) HAL_UART_GetState_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_GetState_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_UART_StateTypeDef cmock_to_return);
#define HAL_UART_GetState_StopIgnore() HAL_UART_GetState_CMockStopIgnore()
void HAL_UART_GetState_CMockStopIgnore(void);
#define HAL_UART_GetState_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_GetState requires _ExpectAndReturn");
#define HAL_UART_GetState_ExpectAndReturn(huart, cmock_retval) HAL_UART_GetState_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const UART_HandleTypeDef* huart, HAL_UART_StateTypeDef cmock_to_return);
#define HAL_UART_GetError_Ignore() TEST_FAIL_MESSAGE("HAL_UART_GetError requires _IgnoreAndReturn");
#define HAL_UART_GetError_IgnoreAndReturn(cmock_retval) HAL_UART_GetError_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_UART_GetError_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define HAL_UART_GetError_StopIgnore() HAL_UART_GetError_CMockStopIgnore()
void HAL_UART_GetError_CMockStopIgnore(void);
#define HAL_UART_GetError_Expect(huart) TEST_FAIL_MESSAGE("HAL_UART_GetError requires _ExpectAndReturn");
#define HAL_UART_GetError_ExpectAndReturn(huart, cmock_retval) HAL_UART_GetError_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const UART_HandleTypeDef* huart, uint32_t cmock_to_return);
#define UART_Start_Receive_IT_Ignore() TEST_FAIL_MESSAGE("UART_Start_Receive_IT requires _IgnoreAndReturn");
#define UART_Start_Receive_IT_IgnoreAndReturn(cmock_retval) UART_Start_Receive_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void UART_Start_Receive_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define UART_Start_Receive_IT_StopIgnore() UART_Start_Receive_IT_CMockStopIgnore()
void UART_Start_Receive_IT_CMockStopIgnore(void);
#define UART_Start_Receive_IT_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("UART_Start_Receive_IT requires _ExpectAndReturn");
#define UART_Start_Receive_IT_ExpectAndReturn(huart, pData, Size, cmock_retval) UART_Start_Receive_IT_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void UART_Start_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define UART_Start_Receive_DMA_Ignore() TEST_FAIL_MESSAGE("UART_Start_Receive_DMA requires _IgnoreAndReturn");
#define UART_Start_Receive_DMA_IgnoreAndReturn(cmock_retval) UART_Start_Receive_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void UART_Start_Receive_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define UART_Start_Receive_DMA_StopIgnore() UART_Start_Receive_DMA_CMockStopIgnore()
void UART_Start_Receive_DMA_CMockStopIgnore(void);
#define UART_Start_Receive_DMA_Expect(huart, pData, Size) TEST_FAIL_MESSAGE("UART_Start_Receive_DMA requires _ExpectAndReturn");
#define UART_Start_Receive_DMA_ExpectAndReturn(huart, pData, Size, cmock_retval) UART_Start_Receive_DMA_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void UART_Start_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
