/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTM32F1XX_HAL_GPIO_H
#define _MOCKSTM32F1XX_HAL_GPIO_H

#include "unity.h"
#include "stm32f1xx_hal_gpio.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockstm32f1xx_hal_gpio_Init(void);
void Mockstm32f1xx_hal_gpio_Destroy(void);
void Mockstm32f1xx_hal_gpio_Verify(void);




#define HAL_GPIO_Init_ExpectAndReturn(GPIOx, GPIO_Init, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_Init requires _Expect (not AndReturn)");
#define HAL_GPIO_Init_Expect(GPIOx, GPIO_Init) HAL_GPIO_Init_CMockExpect(__LINE__, GPIOx, GPIO_Init)
void HAL_GPIO_Init_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, GPIO_InitTypeDef* GPIO_Init);
#define HAL_GPIO_DeInit_ExpectAndReturn(GPIOx, GPIO_Pin, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_DeInit requires _Expect (not AndReturn)");
#define HAL_GPIO_DeInit_Expect(GPIOx, GPIO_Pin) HAL_GPIO_DeInit_CMockExpect(__LINE__, GPIOx, GPIO_Pin)
void HAL_GPIO_DeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint32_t GPIO_Pin);
#define HAL_GPIO_ReadPin_Expect(GPIOx, GPIO_Pin) TEST_FAIL_MESSAGE("HAL_GPIO_ReadPin requires _ExpectAndReturn");
#define HAL_GPIO_ReadPin_ExpectAndReturn(GPIOx, GPIO_Pin, cmock_retval) HAL_GPIO_ReadPin_CMockExpectAndReturn(__LINE__, GPIOx, GPIO_Pin, cmock_retval)
void HAL_GPIO_ReadPin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState cmock_to_return);
#define HAL_GPIO_WritePin_ExpectAndReturn(GPIOx, GPIO_Pin, PinState, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_WritePin requires _Expect (not AndReturn)");
#define HAL_GPIO_WritePin_Expect(GPIOx, GPIO_Pin, PinState) HAL_GPIO_WritePin_CMockExpect(__LINE__, GPIOx, GPIO_Pin, PinState)
void HAL_GPIO_WritePin_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState);
#define HAL_GPIO_TogglePin_ExpectAndReturn(GPIOx, GPIO_Pin, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_TogglePin requires _Expect (not AndReturn)");
#define HAL_GPIO_TogglePin_Expect(GPIOx, GPIO_Pin) HAL_GPIO_TogglePin_CMockExpect(__LINE__, GPIOx, GPIO_Pin)
void HAL_GPIO_TogglePin_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin);
#define HAL_GPIO_LockPin_Expect(GPIOx, GPIO_Pin) TEST_FAIL_MESSAGE("HAL_GPIO_LockPin requires _ExpectAndReturn");
#define HAL_GPIO_LockPin_ExpectAndReturn(GPIOx, GPIO_Pin, cmock_retval) HAL_GPIO_LockPin_CMockExpectAndReturn(__LINE__, GPIOx, GPIO_Pin, cmock_retval)
void HAL_GPIO_LockPin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, HAL_StatusTypeDef cmock_to_return);
#define HAL_GPIO_EXTI_IRQHandler_ExpectAndReturn(GPIO_Pin, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_EXTI_IRQHandler requires _Expect (not AndReturn)");
#define HAL_GPIO_EXTI_IRQHandler_Expect(GPIO_Pin) HAL_GPIO_EXTI_IRQHandler_CMockExpect(__LINE__, GPIO_Pin)
void HAL_GPIO_EXTI_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t GPIO_Pin);
#define HAL_GPIO_EXTI_Callback_ExpectAndReturn(GPIO_Pin, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_EXTI_Callback requires _Expect (not AndReturn)");
#define HAL_GPIO_EXTI_Callback_Expect(GPIO_Pin) HAL_GPIO_EXTI_Callback_CMockExpect(__LINE__, GPIO_Pin)
void HAL_GPIO_EXTI_Callback_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t GPIO_Pin);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
