/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUARTDRIVER_H
#define _MOCKUARTDRIVER_H

#include "unity.h"
#include "UartDriver.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockUartDriver_Init(void);
void MockUartDriver_Destroy(void);
void MockUartDriver_Verify(void);




#define DelayMs_ExpectAndReturn(time_delay, cmock_retval) TEST_FAIL_MESSAGE("DelayMs requires _Expect (not AndReturn)");
#define DelayMs_Expect(time_delay) DelayMs_CMockExpect(__LINE__, time_delay)
void DelayMs_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t time_delay);
#define UartTransmittOneByteData_ExpectAndReturn(transmitted_data, cmock_retval) TEST_FAIL_MESSAGE("UartTransmittOneByteData requires _Expect (not AndReturn)");
#define UartTransmittOneByteData_Expect(transmitted_data) UartTransmittOneByteData_CMockExpect(__LINE__, transmitted_data)
void UartTransmittOneByteData_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t transmitted_data);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
